### ISSUE TITLE
A potential bug related to using uint16 to store AO maps

### ISSUE THREAD

**Issue by husheng12345** [fabiotosi92/NeRF-Supervised-Deep-Stereo#27]
Hello, I've found a potential bug regarding the storage method of AO maps. 
The range of AO is [0,1], it's multiplied by 65536 and then saved as a uint16 PNG image. However, when AO equals exactly 1, 65536 exceeds the maximum value of uint16.  This results in AO being incorrectly stored as 0. 
Here's a visualization example; the white areas in the second image represent where AO=0.
(0005/Q/AO/IMG_20220818_180012.png)
![IMG_20220818_180012](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/8972584/b550e032-97f5-46c1-8888-04df0b8ba0e7)
![temp](https://github.com/fabiotosi92/NeRF-Supervised-Deep-Stereo/assets/8972584/f2b6107d-2dcd-48e3-a3e2-43bdb0ee6563)

**Comment by fabiotosi92** [comment]
Hi!
We're grateful for your observation regarding AO map storage. You're right, when AO is 1, it turns into 0 due to uint16 limits. While we did overlook this issue, it's important to highlight that the exclusion of these points, even though they are highly reliable, is unlikely to have a significant impact on our quantitative results.  This is because these points represent a very low density, and they are generally indicative of regions where stereo matching is relatively easy. 

Once again, thank you for your valuable observation!
